- name: Create a Docker Container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_container_image }}"
    state: started
    ports:
    - "{{ docker_container_ports }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"