---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg2
      - python3-pip
      - python3-setuptools
    state: present

- name: Install Python Docker Module
  pip:
    name: docker

- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers