---
# Grafana

- name: Download Grafana
  get_url:
    url: https://dl.grafana.com/oss/release/grafana_7.3.6_amd64.deb
    dest: /home/deploy/grafana_7.3.6_amd64.deb

- name: Install packages
  apt:
    force_apt_get: yes
    name: "{{ packages }}"

- name: Install Grafana using dpkg
  become: yes
  command: dpkg -i --force-depends /home/deploy/grafana_7.3.6_amd64.deb

- name: Start Grafana
  service: name=grafana-server state=started enabled=yes