# MySQL Container

- name: Create a Docker Container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_container_image }}"
    state: started
    ports:
    - "{{ docker_container_ports }}"
    env:
      MYSQL_ROOT_PASSWORD: "{{ mysql_root_password }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"

# MySQL Exporter

- name: Copy MySQL exporter setup
  copy:
      src: files/exporter.sql
      dest: exporter.sql

- name: Execute setup script in database docker container
  become: yes
  shell: sudo docker exec -i database mysql -uroot -pmicroblog < exporter.sql

- name: Pull mysql_exporter from docker
  become: yes
  shell: docker pull prom/mysqld-exporter

- name: Start mysql_exporter docker container
  command: |
    docker run -d
      -p 9104:9104
      --network host
      -e DATA_SOURCE_NAME="exporter:exporter@(localhost:3306)/"
      --restart always
      prom/mysqld-exporter:latest
      --collect.auto_increment.columns
      --collect.binlog_size
      --collect.engine_innodb_status
      --collect.engine_tokudb_status
      --collect.global_status
      --collect.global_variables
      --collect.info_schema.processlist